#!/bin/sh

sudo apt-get install python3;
sudo apt-get install python3-pip;
sudo apt-get install ruby;
sudo apt-get install screen;
sudo apt-get install git;
mkdir ~/.gf
mkdir ~/Tools;
mkdir ~/Recon;
dir=~/Tools;
go get github.com/Ice3man543/SubOver;
go get -u github.com/tomnomnom/gf;
go get -u github.com/tomnomnom/assetfinder;
apt-get install libpcap-dev;
GO111MODULE=on go get -u -v github.com/projectdiscovery/naabu/v2/cmd/naabu;
go get github.com/tomnomnom/hacks/waybackurls;
go get -u -v github.com/lukasikic/subzy;
go install -v github.com/lukasikic/subzy;
GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei;
git clone https://github.com/projectdiscovery/nuclei-templates $dir/nuclei-templates;
go get github.com/haccer/subjack;
GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
GO111MODULE=on go get -u github.com/projectdiscovery/chaos-client/cmd/chaos;
git clone https://github.com/tillson/git-hound.git $dir/git-hound && cd $dir/git-hound && go install && go build && mv git-hound ~/go/bin/;
go get -u -v github.com/hahwul/dalfox;
go get -u -v github.com/lc/gau;
go get github.com/003random/getJS;
GO111MODULE=on go get -u -v github.com/lc/subjs;
go get github.com/hakluke/hakcheckurl;
go get github.com/hakluke/hakrawler;
go get github.com/hakluke/hakrevdns;
go get -u -v github.com/projectdiscovery/httpx/cmd/httpx;
git clone https://github.com/blechschmidt/massdns $dir/massdns;
git clone https://github.com/devanshbatham/FavFreak $dir/FavFreak;
git clone https://github.com/GerbenJavado/LinkFinder $dir/LinkFinder;
git clone https://github.com/m4ll0k/SecretFinder $dir/SecretFinder;
git clone https://github.com/devanshbatham/ParamSpider $dir/ParamSpider;
go get -u -v github.com/projectdiscovery/dnsprobe;
git clone https://github.com/maurosoria/dirsearch $dir/dirsearch;
git clone https://github.com/ozguralp/gmapsapiscanner $dir/gmapsapiscanner;
go get -u -v github.com/projectdiscovery/shuffledns/cmd/shuffledns;
git clone https://github.com/chenjj/CORScanner.git;
git clone https://github.com/1ndianl33t/Gf-Patterns $dir/Gf-Patterns;
pip3 install -r ~/Tools/requirements.txt;
mv $dir/Gf-Patterns/*.json /root/.gf/;
rm -r $dir/Gf-Patterns;
git clone https://github.com/KathanP19/JSFScan.sh $dir/JSFScan.sh;
mv arsenal ~/arsenal;
cd ~/arsenal;
chmod +x *.sh;
cd $dir/massdns; make;
cp $dir/massdns/bin/massdns /usr/bin/;
cd ~/.gf; wget https://raw.githubusercontent.com/devanshbatham/ParamSpider/master/gf_profiles/potential.json;
cd ~/arsenal; wget https://raw.githubusercontent.com/Ice3man543/SubOver/master/providers.json;
